Repository Project-FallTPS/SkyFall-Resistance_Client, pull requests merged in 2025-05, with the labels that each got.

#9 Feat | 적 상태 머신 구현 | 최민규
  Assets/00. Core/00-20. Util/ELayers.cs
  Assets/00. Core/00-20. Util/ETags.cs
  Assets/00. Core/Damage.cs
  Assets/00. Core/Damage.cs.meta
  Assets/00. Core/IDamageable.cs
  Assets/00. Core/IDamageable.cs.meta
  Assets/00. Core/Object Pool/EnemyPool/EEnemyType.cs
  Assets/03. Mingyu/01. Scene/Test_Mingyu_FallScene.unity
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyData.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyData.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataEditor.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataEditor.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Enemy.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Enemy.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool/EEnemyType.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool/EEnemyType.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool/EnemyPoolInfo.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool/EnemyPoolInfo.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool/EnemyPoolManager.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool/EnemyPoolManager.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EEnemyState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EEnemyState.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyAttackState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyAttackState.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyController.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyController.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDamagedState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDamagedState.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDieState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDieState.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyStateContext.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyStateContext.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyTraceState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyTraceState.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/IEnemyState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/IEnemyState.cs.meta
  Assets/03. Mingyu/08. Materials/Enemy.meta
  Assets/03. Mingyu/08. Materials/Enemy/M_Enemy_Bombing.mat
  Assets/03. Mingyu/08. Materials/Enemy/M_Enemy_Bombing.mat.meta
  Assets/03. Mingyu/08. Materials/Enemy/M_Enemy_Shooting.mat
  Assets/03. Mingyu/08. Materials/Enemy/M_Enemy_Shooting.mat.meta
  Assets/03. Mingyu/08. Materials/Enemy/M_Enemy_Type3.mat
  Assets/03. Mingyu/08. Materials/Enemy/M_Enemy_Type3.mat.meta
  Assets/Editor/LayerEnumGenerator.cs
  Assets/Editor/TagEnumGenerator.cs
Labels: 민규, Feat, Docs, Fix, Add

#10 Feat | 낙하환경 - 박우영
  Assets/03. Mingyu/02. Scripts/02-6. Enviorment.meta
  Assets/03. Mingyu/02. Scripts/02-6. Enviorment/IFalling.cs
  Assets/03. Mingyu/02. Scripts/02-6. Enviorment/IFalling.cs.meta
  Assets/03. Mingyu/02. Scripts/02-6. Enviorment/ParallaxLayer.cs
  Assets/03. Mingyu/02. Scripts/02-6. Enviorment/ParallaxLayer.cs.meta
  Assets/03. Mingyu/02. Scripts/02-6. Enviorment/ParallaxManager.cs
  Assets/03. Mingyu/02. Scripts/02-6. Enviorment/ParallaxManager.cs.meta
  Assets/04. Uyeong/01. Scene/Test_WooYoung_FallScene.unity
Labels: 우영, Feat

#11 Docs | 스크립트 위치 이동
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment.meta
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/IFalling.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/IFalling.cs.meta
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/ParallaxLayer.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/ParallaxLayer.cs.meta
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/ParallaxManager.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/ParallaxManager.cs.meta
Labels: 우영, Docs

#16 Feat | 활성화된 적 GO를 담는 HashSet 추가
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Pool/EnemyPoolManager.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Spawner/EnemySpawner.cs
Labels: 민규, Feat

#22 Feat | Layer이동루프-박우영
  Assets/04. Uyeong/01. Scene/Test_WooYoung_FallScene.unity
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/ParallaxLayer.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/ParallaxManager.cs
Labels: 우영, Feat

#24 Feat | EnemyDataSO 설계 및 상태 변화에 따른 애니메이션 트랜지션 구현 - 최민규
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Animation.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Animation/EEnemyAnimationTransitionParam.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Animation/EEnemyAnimationTransitionParam.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyData.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataEditor.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataEditor.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataSO.asset
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataSO.asset.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataSO.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemyDataSO.cs.meta
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Data/EnemySO.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyAttackState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyController.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDamagedState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDieState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyTraceState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Strategy/Trace/TraceBezier.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Strategy/Trace/TraceNormal.cs
  Assets/03. Mingyu/03. Prefabs/Enemy/P_Enemy_Bombing.prefab
  Assets/03. Mingyu/03. Prefabs/Enemy/P_Enemy_Shooting.prefab
Labels: 민규, Feat, Style

#28 Feat | Fluffy Cloud-박우영
  Assets/04. Uyeong/01. Scene/Test_WooYoung_FallScene.unity
  Assets/04. Uyeong/03. Prefabs/Clouds.prefab
  Assets/04. Uyeong/03. Prefabs/Clouds.prefab.meta
  Assets/04. Uyeong/08. Materials/CloudMaterial.mat
  Assets/04. Uyeong/08. Materials/CloudMaterial.mat.meta
  Assets/04. Uyeong/08. Materials/CloudParticleShader.shadergraph
  Assets/04. Uyeong/08. Materials/CloudParticleShader.shadergraph.meta
  Assets/04. Uyeong/08. Materials/CloudShader.shadergraph
  Assets/04. Uyeong/08. Materials/CloudShader.shadergraph.meta
  Assets/04. Uyeong/20. External Assets/SM_Sphere_CloudParticles.fbx
  Assets/04. Uyeong/20. External Assets/SM_Sphere_CloudParticles.fbx.meta
  Assets/04. Uyeong/20. External Assets/T_Noise_CloudParticles.png
  Assets/04. Uyeong/20. External Assets/T_Noise_CloudParticles.png.meta
Labels: 우영, Feat, Add

#32 Refactor | Bezier 전략 및 적 상태 머신 개선
  Assets/03. Mingyu/01. Scene/Test_Mingyu_FallScene.unity
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyAttackState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDieState.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Strategy/Trace/TraceBezier.cs
  Assets/03. Mingyu/03. Prefabs/Enemy/P_Enemy_Bombing.prefab
  Assets/03. Mingyu/03. Prefabs/Enemy/P_Enemy_Shooting.prefab
Labels: 민규, Refactor

#43 Style | 잔해물효과추가 박우영
  Assets/04. Uyeong/01. Scene/Test_WooYoung_FallScene.unity
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Debris/Debris.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Debris/ExplosiveDebris.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Debris/FirePositionUpdater.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Debris/FirePositionUpdater.cs.meta
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Debris/NormalDebris.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Debris/Spawner/DebrisSpawner.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Parallax.meta
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Parallax/ParallaxLayer.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Parallax/ParallaxLayer.cs.meta
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Parallax/ParallaxManager.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Parallax/ParallaxManager.cs.meta
  Assets/04. Uyeong/03. Prefabs/Debris/P_Debris_Explosive.prefab
  Assets/04. Uyeong/03. Prefabs/Debris/P_Debris_Normal.prefab
  Assets/04. Uyeong/08. Materials/CloudParticleShader.shadergraph
  Assets/04. Uyeong/20. External Assets/GabrielAguiarProductions/Prefabs/StylizedSmoke/vfxgraph_StylizedSmoke_v1_Fire.prefab
  Assets/04. Uyeong/20. External Assets/GabrielAguiarProductions/Prefabs/VFXGraphs/vfxgraph_StylizedSmoke_v1.vfx
  Assets/04. Uyeong/20. External Assets/GabrielAguiarProductions/Shaders/SmokeShader_v1_01.shadergraph
Labels: 우영, Style

#49 Feat | 보스BT 곡사 구현
  Assets/03. Mingyu/01. Scene/Test_Mingyu_BossScene.unity
  Assets/03. Mingyu/01. Scene/Test_Mingyu_BossScene/NavMesh-======= [ Map ] =======.asset
  Assets/03. Mingyu/01. Scene/Test_Mingyu_BossScene/NavMesh-======= [ Map ] =======.asset.meta
  Assets/03. Mingyu/02. Scripts/02-1. Core/Damageable/EDamageableType.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Strategy/Attack/Shooting/AttackShooting.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/Strategy/Attack/Shooting/Bullet.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet.meta
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/BezierBullet.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/BezierBullet.cs.meta
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/BulletBase.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/BulletBase.cs.meta
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/StraightBullet.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/StraightBullet.cs.meta
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Behavior Tree/BossShootAction.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Behavior Tree/BossTraceAction.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/BossController.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Data/BossDataSO.asset
  Assets/03. Mingyu/03. Prefabs/Boss/P_BulletBezier_Boss.prefab
  Assets/03. Mingyu/03. Prefabs/Boss/P_BulletBezier_Boss.prefab.meta
  Assets/03. Mingyu/03. Prefabs/Boss/P_BulletStraight_Boss.prefab
  Assets/03. Mingyu/03. Prefabs/Boss/P_BulletStraight_Boss.prefab.meta
Labels: 민규, Feat

#50 Style | Layer 환경 추가 세팅 - 박우영
  Assets/04. Uyeong/01. Scene/Test_WooYoung_FallScene.unity
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Parallax/ParallaxLayer.cs
  Assets/04. Uyeong/02. Scripts/02-6. Enviorment/Parallax/ParallaxManager.cs
  Assets/04. Uyeong/03. Prefabs/Cloud.meta
  Assets/04. Uyeong/03. Prefabs/Cloud/ConeClouds.prefab
  Assets/04. Uyeong/03. Prefabs/Cloud/ConeClouds.prefab.meta
  Assets/04. Uyeong/03. Prefabs/Cloud/DonutClouds.prefab
  Assets/04. Uyeong/03. Prefabs/Cloud/DonutClouds.prefab.meta
  Assets/04. Uyeong/03. Prefabs/Debris/P_Debris_Explosive.prefab
  Assets/04. Uyeong/03. Prefabs/EnvironmentRoot.prefab
  Assets/04. Uyeong/03. Prefabs/EnvironmentRoot.prefab.meta
Labels: 우영, Style

#53 Feat | SceneEnumGenerator 구현
  Assets/00. Core/00-20. Util/ESceneNames.cs
  Assets/00. Core/00-20. Util/ESceneNames.cs.meta
  Assets/Editor/SceneEnumGenerator.cs
  Assets/Editor/SceneEnumGenerator.cs.meta
Labels: 민규, Feat

#55 Style | 프로토타입 scene 병합
  Assets/00. Core/00-20. Util/ETags.cs
  Assets/00. MaIn/01. Scenes/FallScene.unity
  Assets/01. Sumin/02. Scripts/Player/AttackStrategies/TargetManager.cs
  Assets/03. Mingyu/02. Scripts/02-3. Enemy/State/EnemyDieState.cs
  Assets/03. Mingyu/03. Prefabs/Enemy/P_Enemy_Bombing.prefab
  Assets/03. Mingyu/03. Prefabs/Enemy/P_Enemy_Shooting.prefab
Labels: 민규, 우영, 수민, 미르, Style

#58 Fix | FrustumUI FIxed
  Assets/00. MaIn/01. Scenes/FallScene.unity
  Assets/02. Mir/02. Scripts/InGame1_Misc/InGame1_TargetingCheckerFrustumUpdater.cs
Labels: Fix

#62 Add | LobbyScene Added
  Assets/00. MaIn/01. Scenes/LobbyScene.unity
Labels: 미르, Add

#70 Feat | 보스 약점공격 시스템
  Assets/00. Core/00-20. Util/ETags.cs
  Assets/01. Sumin/02. Scripts/Player/AttackStrategies/TargetManager.cs
  Assets/03. Mingyu/01. Scene/Test_Mingyu_BossScene.unity
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Behavior Tree/BossLaserAction.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Behavior Tree/BossRushAction.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/BossController.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Data/BossData.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Data/BossDataSO.asset
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Data/BossDataSO.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/PhaseManager.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/WeaknessCollider.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/WeaknessCollider.cs.meta
  Assets/03. Mingyu/03. Prefabs/Boss/P_Boss.prefab
  Assets/03. Mingyu/03. Prefabs/Boss/P_Boss_WeaknessCollider.prefab
  Assets/03. Mingyu/03. Prefabs/Boss/P_Boss_WeaknessCollider.prefab.meta
  Assets/20. External Assets/ThirdParty.meta
  Assets/20. External Assets/ThirdParty/AmyElliott.meta
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue.meta
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue/LICENSE.md
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue/LICENSE.md.meta
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue/README.md
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue/README.md.meta
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue/Scripts.meta
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue/Scripts/PriorityQueue.cs
  Assets/20. External Assets/ThirdParty/AmyElliott/PriorityQueue/Scripts/PriorityQueue.cs.meta
  ProjectSettings/TagManager.asset
Labels: 민규, Feat

#72 Refactor | 보스 전반적인 개선
  Assets/03. Mingyu/01. Scene/Test_Mingyu_BossScene.unity
  Assets/03. Mingyu/02. Scripts/02-1. Core/Damageable/EDamageableType.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/BezierBullet.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/BezierBullet.cs.meta
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/BulletBase.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/CurveBullet.cs
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/CurveBullet.cs.meta
  Assets/03. Mingyu/02. Scripts/02-7. Environment/Bullet/StraightBullet.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Behavior Tree/BossShootAction.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Behavior Tree/CheckAttackCoolDownAction.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Data/BossData.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Data/BossDataSO.asset
  Assets/03. Mingyu/03. Prefabs/Boss/P_Boss.prefab
  Assets/03. Mingyu/03. Prefabs/Boss/P_BulletHermitCurve_Boss.prefab
  Assets/03. Mingyu/03. Prefabs/Boss/P_BulletHermitCurve_Boss.prefab.meta
  Assets/03. Mingyu/03. Prefabs/Boss/P_BulletStraight_Boss.prefab
Labels: 민규, Feat, Refactor

#77 Add | Resource added
  Assets/00. MaIn/01. Scenes/FallScene.unity
  Assets/01. Sumin/01. Scenes/FallSceneTest.unity
  Assets/02. Mir/03. Prefabs/Katana.prefab
  Assets/02. Mir/03. Prefabs/Katana.prefab.meta
  Assets/02. Mir/03. Prefabs/PlayerWithModel.prefab
  Assets/02. Mir/03. Prefabs/PlayerWithModel.prefab.meta
  Assets/02. Mir/05. Models/HeliWing.fbx
  Assets/02. Mir/05. Models/HeliWing.fbx.meta
  Assets/02. Mir/05. Models/JetPack.fbx
  Assets/02. Mir/05. Models/JetPack.fbx.meta
  Assets/20. External Assets/Kyeoms_FX/Prefabs/New Stylized Explosion Package/FX_Firesmoke_1.prefab
Labels: 수민, 미르, Add

#78 Hotfix | 에르미트 곡사 수정
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Behavior Tree/BossShootAction.cs
  Assets/03. Mingyu/02. Scripts/02-8. Boss/Data/BossData.cs
Labels: Fix

#91 Add | LobbyScene Model 추가 및 Camera 연출 추가
  Assets/00. MaIn/01. Scenes/LobbyScene.unity
  Assets/02. Mir/02. Scripts/Camera/CustomAxisFeeder.cs
  Assets/02. Mir/02. Scripts/Camera/CustomAxisFeeder.cs.meta
  Assets/02. Mir/05. Models/LobbyScene.fbx
  Assets/02. Mir/05. Models/LobbyScene.fbx.meta
  Assets/02. Mir/08. Materials/LobbyMatarials.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Door_Main.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Door_Main.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Door_Wall.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Door_Wall.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Frame.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Frame.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Granish.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Granish.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Material.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Material.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Below.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Below.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Ceilling.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Ceilling.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Floor.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Floor.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Light.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Light.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Middle.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Middle.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Pillar.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Pillar.mat.meta
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Pipe.mat
  Assets/02. Mir/08. Materials/LobbyMatarials/Wall_Pipe.mat.meta
Labels: 미르, Feat, Add

#94 Add / Feat | Lobby Scene 기능구현 및 디자인
  Assets/00. MaIn/01. Scenes/LobbyScene.unity
  Assets/01. Sumin/02. Scripts/UI/Monitor/MonitorButtonController.cs
  Assets/02. Mir/01. Scenes/IntroScene.unity
  Assets/02. Mir/01. Scenes/IntroScene.unity.meta
  Assets/02. Mir/02. Scripts/Lobby_Misc/LobbySceneManager.cs
  Assets/02. Mir/02. Scripts/Lobby_Misc/LobbySceneManager.cs.meta
  Assets/02. Mir/02. Scripts/Lobby_Misc/UI_ExitPanel.cs
  Assets/02. Mir/02. Scripts/Lobby_Misc/UI_ExitPanel.cs.meta
  Assets/02. Mir/02. Scripts/Lobby_Misc/UI_OptionPanel.cs
  Assets/02. Mir/02. Scripts/Lobby_Misc/UI_OptionPanel.cs.meta
  Assets/02. Mir/03. Prefabs/01_LobbyScene.meta
  Assets/02. Mir/03. Prefabs/01_LobbyScene/ExitPanel.prefab
  Assets/02. Mir/03. Prefabs/01_LobbyScene/ExitPanel.prefab.meta
  Assets/02. Mir/03. Prefabs/01_LobbyScene/LobbySceneManager.prefab
  Assets/02. Mir/03. Prefabs/01_LobbyScene/LobbySceneManager.prefab.meta
  Assets/02. Mir/03. Prefabs/01_LobbyScene/OptionPanel .prefab
  Assets/02. Mir/03. Prefabs/01_LobbyScene/OptionPanel .prefab.meta
  Assets/02. Mir/03. Prefabs/01_LobbyScene/PerkEquipPanel.prefab
  Assets/02. Mir/03. Prefabs/01_LobbyScene/PerkEquipPanel.prefab.meta
  Assets/02. Mir/03. Prefabs/01_LobbyScene/PosCam_Archive.prefab
  Assets/02. Mir/03. Prefabs/01_LobbyScene/PosCam_Archive.prefab.meta
  Assets/02. Mir/03. Prefabs/01_LobbyScene/UI_Monitor.prefab
  Assets/02. Mir/03. Prefabs/01_LobbyScene/UI_Monitor.prefab.meta
  Assets/02. Mir/03. Prefabs/01a_IntroScene.meta
  Assets/02. Mir/03. Prefabs/01a_IntroScene/BattleShip.prefab
  Assets/02. Mir/03. Prefabs/01a_IntroScene/BattleShip.prefab.meta
  Assets/02. Mir/03. Prefabs/02_FallScene.meta
  Assets/02. Mir/05. Models/BattleShip 1.fbx
  Assets/02. Mir/05. Models/BattleShip 1.fbx.meta
Labels: 수민, 미르, Feat, Docs, Add

#96 Docs | 로비신 구조변경
  Assets/00. MaIn/01. Scenes/LobbyScene.unity
Labels: Docs

#97 Add | Alert UI 프리팹 추가
  Assets/02. Mir/02. Scripts/InGame1_UI/InGame1_UI_PlayerOutBoundaryAlert.cs
  Assets/02. Mir/03. Prefabs/02_FallScene/Panel_OutOfBoundaryUI.prefab
  Assets/02. Mir/03. Prefabs/02_FallScene/Panel_OutOfBoundaryUI.prefab.meta
Labels: Feat, Add
